language: java
sudo: false

jdk: oraclejdk11

addons:
   sonarcloud:
      organization: eskaton-github

install: true

script:
   - mvn -e -B clean org.jacoco:jacoco-maven-plugin:prepare-agent install org.jacoco:jacoco-maven-plugin:report sonar:sonar -Dsonar.login=$SONAR_TOKEN -Dsonar.projectKey=eskaton_commons

cache:
   directories:
      - '$HOME/.m2/repository'
      - '$HOME/.sonar/cache'
